### ISSUE TITLE
Meshswap adds extra entities

### ISSUE THREAD

**Issue by Zachadactyl** [TheDuckCow/MCprep#411] opened 2023-03-27 01:27 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When trying to mesh swap doors, torches, pumpkins, ladders, and grass, the plugin places blocks in odd locations, while fixing the ones in correct locations.  And for doors, it appears the bottom 1/2 of the door is repeated three times stacked, and looks bad.  I am unable to send screenshots due to having a potato PC, but I will try to hop onto the desktop soon.  

### What steps are needed to produce the bug?

1) Install MCreator 3.4.3
2) Import a scene via OBJ Import button in MCprep
3) Hit A, then click mesh swap.  After it loads, notice the misplaced blocks

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

Blender 3.4.1

**Comment by StandingPadAnimations** [comment] 2023-03-28 00:09
Without screenshots, I'm not sure what the issue is, but I'll assume it's simillar to #118

**Comment by StandingPadAnimations** [comment] 2023-03-30 15:21
> Yes, it's exactly like that.  That was 2020, will it get a fix soon?

Not likely in the near future, we have higher priorities and not enough manpower to fix older bugs

**Comment by TheDuckCow** [comment] 2023-07-10 01:38
Closing this as a duplicate, since we indeed have this logged in the issue mentioned. Per StandingPad's point, these are known issues, but he has recently started a proposal on a replacement system that would allow us to restart development on Meshswap, allowing us to more flexible handle cases and fix things like this. Still a ways out though.

**Closed by TheDuckCow** 2023-07-10 01:38 UTC
Labels: user-troubleshoot
