### ISSUE TITLE
Can MeshSwap replace faces?

### ISSUE THREAD

**Issue by ghost** [TheDuckCow/MCprep#56] opened 2018-10-10 07:42 UTC
I've been looking for a way to replace default block exports to extruded blocks, but when I replaced the MeshSwap blocks with my own, it kinda worked, I didn't expect something like this to happen:

<img width="778" alt="screenie30" src="https://user-images.githubusercontent.com/42160166/46719823-c670c100-cc23-11e8-896b-849327aff9bb.PNG">

it worked! or that's what I thought...

<img width="833" alt="screenie31" src="https://user-images.githubusercontent.com/42160166/46719952-12bc0100-cc24-11e8-8f0e-9b6525cd6ea5.PNG">

it replaced the entire block and their faces were clipping, then thought of modifying the model to only be 1 side of the 6 sides of the block, and it didn't work because MeshSwap replaces blocks for models.

so what if instead of replacing from the block's origin, it replaced from the faces?

something like this:

<img width="1036" alt="screenie32" src="https://user-images.githubusercontent.com/42160166/46720366-359ae500-cc25-11e8-9351-60a2073ba67c.PNG">

<img width="1018" alt="screenie33" src="https://user-images.githubusercontent.com/42160166/46720393-4186a700-cc25-11e8-9901-0b01e69315a8.PNG">

is it possible to do that?

**Comment by TheDuckCow** [comment] 2018-10-11 10:57
Hey there,

The use case you show should work and I have used it myself. I wonder if it has to do with selecting the right exporter. Note that indeed it will only replace the entire block, not just faces of a block.

Firstly, are you using mineways or jmc2obj? 

Secondly, did you press meshswap when the matching exporter was highlighted in blue at the top of that panel? If you have a Mis-match, strange like your first screenshot will happen. 

Thirdly, what version of MCprep are you using, the latest 3.1.0?

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by Zophiekat** [comment] 2018-10-11 15:09
Hi,

I used Mineways ro export the world and yes I did press mesh swap with the correct exporter, and I'm using 3.1.0

**Comment by TheDuckCow** [comment] 2018-10-11 22:48
Do you mind sharing the world export you used? You should be able to attach the blend file to a reply here directly. And also attach the file with the custom block you are trying to use, definitely think I can get this working for you. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment] 2018-10-19 02:42
Sorry for the delay, thanks for packaging all this together. My notes in response:

1. Did you know, there actually already is a block in the meshswap file (layer 20) for the stone brick? I just didn't duplicate it for the Mineways name; if you rename the block "stone_brick" to "Stone_Bricks" exactly, then you can use this already built in block (it's scaled in ever so slightly compared to your model, though this technically creates "see through" cracks)
2. You're right, it's not functioning correctly in some parts of your world for Mineways. Not not sure yet what the root cause is, but this work around works for your file on the stone bricks (some of the other blocks like grass seem to meshswap okay though):
    - Go into edit mode on the stone brick
    - Select all faces (press a)
    - While in edit mode, translate it by 0.5 units in xyz directions (e.g. keystrokes: `g`, `x`, `.5`, `enter`, `g`, `y`, `.5`, `enter`, `g`, `z`, `.5`, `enter`)
    - Press tab to return to object mode, and now in _object_ mode do the "inverse" by translating it by -0.5 units in xyz directions (e.g. keystrokes: `g`, `x`, `-.5`, `enter`, `g`, `y`, `-.5`, `enter`, `g`, `z`, `-.5`, `enter`)
    - Change your world mode to "jmc2obj" (yes, even though it was really Mineways)
    - NOW you can press meshswap, and should find it works (and then prep materials, to get it back in cycles mode)

If the above process seems strange, in short it's related somehow to the face that mineways worlds vs jmc2obj worlds have their block origins offset by 0.5 units compared to each other, so by moving it half a unit in object space that makes it work with the jmc2obj logic which looks where faces and vertices are located to indicate how to do swapping. 

Rather annoying to do right now I realize, but it's at least only one step per import if you join all objects together first before doing the offsetting. Also if you're fine with just having everything moved together by 0.5 units, and you do it to the whole world at once, then you can skip the step above where you moved it by negative -0.5.

Let me know if this helps, and thanks again for opening the issue here.

**Comment by Zophiekat** [comment] 2018-10-19 02:49
Moving the block -0.5 seems to work :)

**Comment by TheDuckCow** [comment] 2018-10-19 02:52
Great - if you notice any further patterns (e.g. if that's only true for some blocks, or not others) as well as come up with any other oddities, please please let me know :) To be entirely honest, the meshswap feature has always been rough around the edges, but I'm looking to improve where it matters. Things like orienting doors and stairs the right way is hard, but doable as examples, but I'm sure there are more oddities as I've not tried meshswaping every kind of block myself.

**Comment by Zophiekat** [comment] 2018-10-19 03:04
MeshSwap is one of my favorite functions in McPrep, but I have few understanding of it, respect to the blocks orientation we could use some sort of block state just like jmc does

**Comment by TheDuckCow** [comment] 2020-09-28 14:51
Closing this issue after literal years as, with my most recent test, the meshswap function indeed works fine on the Mineways combined texture output (with a slight meshswap asset improvement happening in v3.2.4)

**Closed by TheDuckCow** 2020-09-28 14:51 UTC
Labels: bug
