### ISSUE TITLE
MCPREP 3.2.0 Not working for Blender 2.7.9

### ISSUE THREAD

**Issue by HijackAssassin** [TheDuckCow/MCprep#73] opened 2019-06-29 20:33 UTC
https://user-images.githubusercontent.com/52359898/60389145-dc146800-9a8a-11e9-9372-486779ea7490.PNG

**Comment by SoundBlast** [comment] 2019-06-30 17:01
I am also having the same problem
![Capture](https://user-images.githubusercontent.com/47902287/60399735-09f6bc80-9b1e-11e9-9191-40c86a397b30.PNG)

**Comment by TheDuckCow** [comment] 2019-07-01 10:50
Hi,

In both of these cases, can you please try removing MCprep entirely, *closing blender*, and then re-installing it? The errors looks like those I'd expect to see if blender wasn't closed after installing an update. I can confirm from my side that MCprep's current version is working generally on 2.79 on both mac and windows.

**Comment by TheDuckCow** [comment] 2019-07-17 12:45
Looking for a follow up from either of you, to see if the above steps resolved the problem.

**Comment by TheDuckCow** [comment] 2019-08-05 01:01
Closing in the meantime, in general the key is fully removing the addon, closing blender and re-opening and installing fresh.

**Closed by TheDuckCow** 2019-08-05 01:01 UTC
