### ISSUE TITLE
Mesh swap torch light

### ISSUE THREAD

**Issue by Enderminer** [TheDuckCow/MCprep#201] opened 2021-04-19 15:25 UTC
### Issue
Point lights on certain torches not working after mesh swap.
#### Description

I have a section of a world imported and I selected the torches in the world (It's 500 torches, my system is able to handle it). Certain lights don't work. It seems almost completely random and I'm not sure what's up. I checked out the *mcprep_meshSwap.blend* but nothing seemed wrong with the point light in that one and the point lights that do function work fine. I'm not sure if this is a blender issue or a MCprep issue but I've never experienced this before.

![Torches working on right side but not left](https://i.imgur.com/NnnQ9mj.png)

**Comment by TheDuckCow** [comment] 2021-04-19 15:27
Just double checking, can you remove MCprep full and then reinstall it? (installing without removing first won't work). I say this because I recently release a new MCprep version which should have fixed this very issue.

**Comment by Enderminer** [comment] 2021-04-19 16:12
I've done that and experienced a different issue.

Torches having no texture in the *mcprep_meshSwap.blend*

![Torches without textures.](https://i.imgur.com/pMdTZzR.png)

I found this odd as they had all the proper nodes in the shader editor. That's when I realized that "Use Nodes" was disabled with both materials:

![Use Nodes Disabled](https://i.imgur.com/uD0Q8tG.png)

Now they look like this:

![Torches with most textures](https://i.imgur.com/WmTbzFi.png)

The top is missing but it wasn't that big of a deal so I thought I'd give it another go.
 
 I made a new blender file, imported the world, prepped the materials, and swapped the torch mesh and...

![Same issue](https://i.imgur.com/Zz8fkzN.png)

The *exact* same issue.

Not sure what's going on with it.

**Comment by REIGNjs** [comment] 2021-05-25 16:39
I am experiencing the same issue. "torch_on.main" is missing the use node property for its material and is missing the animation (see screenshot). 
![image](https://user-images.githubusercontent.com/64702286/119535540-67d2c400-bd88-11eb-8808-e3836b35a772.png)

**Comment by TheDuckCow** [comment] 2021-06-08 12:01
Marking this as resolved as I've done some minor asset updates, and confirmed in my own test file that the lamps should be properly assigned to the separate groups. Please wait for the v3.2.5 release coming later today, and be sure to either use the in-addon updater (which will auto overwrite the meshswap blend file), or manually delete MCprep, close blender, and then reinstall using the install addon flow in user preferences.

**Closed by TheDuckCow** 2021-06-08 12:01 UTC
Labels: user-troubleshoot
