### ISSUE TITLE
Black grass in render.

### ISSUE THREAD

**Issue by iPandax** [TheDuckCow/MCprep#377] opened 2023-03-02 18:04 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

![Screenshot 2023-03-02 at 17 56 23](https://user-images.githubusercontent.com/126812365/222512064-22a73c85-d25a-4fae-997d-25a8a12c7132.png)
FWs
![Screenshot 2023-03-02 at 17 57 34](https://user-images.githubusercontent.com/126812365/222512263-b8af3ac8-8bb1-4223-952e-7e7221d9b58f.png)
I expected the materials to prep like normal. In the material view they are fine, but they render black and the solid view (texture) shows up grey. I have noticed this for other vegetation like seeds and seagrass.

### What steps are needed to produce the bug?

Import a world via mine ways and prep the materials. I have done some other scene setup for trees, but that isn't relevant.

### What version of MCprep are you using?

3.4.1.

### What version of Blender are you using?

3.4.

**Comment by iPandax** [comment] 2023-03-02 18:06
Thanks for any replies!

**Comment by iPandax** [comment] 2023-03-02 18:13
alpha hashed

**Comment by StandingPadAnimations** [comment] 2023-03-02 18:17
Ok, have you tried going into edit mode on the grass, selecting every face, and pressing Alt M with the "merge by distance" option? I assume you're using Mineways, which in that case this is nothing new

**Comment by iPandax** [comment] 2023-03-02 18:32
![Screenshot 2023-03-02 at 18 31 24](https://user-images.githubusercontent.com/126812365/222519884-1d444dc2-7633-4202-b1ab-c9ddb9d180e8.png)
This ended up happening - fyi yes I'm using mine ways.

**Comment by StandingPadAnimations** [comment] 2023-03-06 21:22
Yeah I'm not sure what's going, can you send the file?

**Comment by iPandax** [comment] 2023-03-06 21:37
BTW thanks for all the help, this has been bugging me for a while

**Comment by StandingPadAnimations** [comment] 2023-03-06 21:39
> It says it doesn't support the .blend format

Will a zip file work? Btw, make sure everything has been packed to the blend file

**Comment by iPandax** [comment] 2023-03-06 21:42
Got it, thanks
[SpeedrunShot1.zip](https://github.com/TheDuckCow/MCprep/files/10903010/SpeedrunShot1.zip)

**Comment by StandingPadAnimations** [comment] 2023-03-06 21:43
No problem, I'll take a look at it once I get the chance (either today or tomorrow)

**Comment by StandingPadAnimations** [comment] 2023-03-07 04:58
@iPandax I can't reproduce the issue on my end, are you using a GPU? If so, does enabling CPU rendering help? 

The grey grass I'm not concerned with since solid mode just shows the actual texture itself, but MCprep sets the color in the material
![image](https://user-images.githubusercontent.com/75058058/223324569-8c4eaaf5-cbda-442f-9eab-0ece65ed52f3.png)

**Comment by iPandax** [comment] 2023-03-07 09:46
And i'm already using cpu

**Comment by iPandax** [comment] 2023-03-09 10:36
hello?

**Comment by StandingPadAnimations** [comment] 2023-03-10 18:40
Sorry about that. It looks like an issue with both Mineways (Mineways exports in a weird way). I've also noticed you're using Blender 3.3, and so far I haven't really seen any of the black spots in Blender 3.4 (then again I'm on my laptop, so Cycles has been a pain for me in general)

There's really not much we can do, it's an issue with the OBJ itself. My best recommendation would be to either:
- Update to Blender 3.4 and see if that resolves the issue
- Update Mineways and reexport the world (or if you're already using the latest version of Mineways, see if [simplify mesh](https://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#simplify) helps)
- If Blender 3.4 doesn't resolve the issue, then avoid Mineways and use jmc2OBJ

I'll be closing this since it doesn't relate to MCprep, but you'll still be able to comment here

**Closed by StandingPadAnimations** 2023-03-10 18:40 UTC
Labels: user-troubleshoot

**Comment by iPandax** [comment] 2023-03-11 11:59
Thanks! I will try this
