### ISSUE TITLE
Meshswap Causing issues

### ISSUE THREAD

**Issue by KittenCat1080ti** [TheDuckCow/MCprep#158] opened 2020-09-26 20:57 UTC
I was doing a meshswap on a world of mine and the result was all the carrots were supersized and some of the meshswapped blocks were deleted, leaving holes in the world, Stone bricks were affected by this

**Comment by KittenCat1080ti** [comment] 2020-09-27 12:32
Other effects include an extremely laggy timeline. Low memory usage, but very high cpu usage

**Comment by TheDuckCow** [comment] 2020-09-27 13:36
As per the [tutorial here](https://www.youtube.com/watch?v=3gbrOkqmqRE&list=PL8X_CzUEVBfaa9PD9lWm4HdQCxUhl62Zb&index=12), Meshswap is honestly best used when intentionally ran for specific blocks instead of trying to select everything at once. 

Inherently based on the way meshswap works, the first step it takes is to split all materials into their own objects, which is why you are seeing that. It then does a lookup of those materials to objects 

I'll see about trying to improve the stone and carrot meshswap object, but in the meantime, I'd recommend intentionally selecting the blocks you want to meshswap - and even further limiting to just those near the camera, so you don't bog your computer down too hard!

**Comment by KittenCat1080ti** [comment] 2020-09-27 15:22
Thank you, I did this. I can manage the performance issues :). I wish you luck in fixing the stone bricks and carrots meshswap. note: this happens with potatoes too.

**Comment by TheDuckCow** [comment] 2020-09-27 16:09
Does anything in you scene come in with the proper scale, or is everything off?

**Comment by KittenCat1080ti** [comment] 2020-09-27 16:17
Everything is normal apart from the carrots and potatoes note the normal size lantern (I meshswapped that) and the Crazy sized potatoes. Carrots are supersized too

![Thing](https://user-images.githubusercontent.com/71938947/94370015-326fbc80-00bb-11eb-9135-5334a9613e03.png)

**Comment by TheDuckCow** [comment] 2020-09-27 17:19
Thanks for this, I see what the issue is - the objects in the meshswap file did not have scale applied so they were reset on meshswap. Potatoes and carrots will thus be fixed in the next release. I've also now locally edited the stone brick so that it should not have holes poking through like you identified. There ends up being a little overlap between adjacent blocks, but not too bad/noticeable.

Closing this issue - this will be address int he v3.2.4 release!

**Closed by TheDuckCow** 2020-09-27 17:19 UTC
Labels: user-troubleshoot
