### ISSUE TITLE
On Blender I can't use the MCprep addon, Please help me!

### ISSUE THREAD

**Issue by JERBEAR3452** [TheDuckCow/MCprep#18] opened 2017-04-11 00:09 UTC
On Blender I can't use the MCprep addon, please help me!

**Comment by TheDuckCow** [comment] 2017-04-12 07:42
@JERBEAR3452 please try the [latest version of MCprep](theduckcow.com/dev/blender/mcprep-download/), 3.0.1 to see if your problem is solved. If not, please report which version of blender you are using and share the screenshot indicating what is not working

**Comment by TheDuckCow** [comment] 2017-05-07 05:40
@JERBEAR3452 just checking, is your issue fixed?

**Comment by ThePoptartCrpr** [comment] 2017-05-07 15:36
I'm having issues with it as well. When I try to click the check box in the addons menu, I get this error:
![screenshot 148](https://cloud.githubusercontent.com/assets/25708063/25782454/4855915a-3300-11e7-92c2-a00b98b1fe55.png)

**Comment by TheDuckCow** [comment] 2017-05-07 15:37
Yup I realized today what the issue is, and have fixed it in dev - I will be trying to release this new update (v3.0.2) as soon as possible. Thanks for sharing the screenshot and apologies for the issue

**Comment by ThePoptartCrpr** [comment] 2017-05-07 15:39
I'm having issues with it as well. When I try to click the check box next to it in the addons menu to enable it, I get this error:
![screenshot 148](https://cloud.githubusercontent.com/assets/25708063/25782474/92e587ac-3300-11e7-971d-73de0343219b.png)

EDIT: Ah, thanks. Realized I forgot to censor my /user/ username and went back to edit it lol

**Comment by TheDuckCow** [comment] 2017-05-24 22:28
@ThePoptartCrpr and @JERBEAR3452 please confirm if able that you can use the latest MCprep (v3.0.2) on your versions of blender, which I see included 2.73 above. I have personally tested on blender 2.72 so I imagine it should also now work for you as well.

**Comment by Axelen123** [comment] 2017-05-25 09:06
sorry for posting this here but I am using blender 2.77 and I dont know which version supports 2.77 I tried the latest one and it does not seem to work because I cant enable it

**Comment by TheDuckCow** [comment] 2017-05-25 11:45
Can you please share a screenshot of the error while enabling? 2.77 should work fine.

**Comment by Axelen123** [comment] 2017-05-26 16:45
https://photos.google.com/photo/AF1QipNQtV8yAA9JUmwli5sPBMXUHCbykUaESRh35v9k?hl=sv
(sorry I had to take the photo with my phone because if I moved my mouse too much the error report would just disappear)

**Comment by TheDuckCow** [comment] 2017-05-26 18:27
Think I don't have permission to see - can you add set it so that anyone with the link can view? Or just directly upload the image through the github comment section itself. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by Axelen123** [comment] 2017-05-26 18:43
I edited the comment so now it shows the actual image

**Comment by TheDuckCow** [comment] 2017-05-26 20:22
Perfect I see it now. Will look into this shortly, it's not one I've seen with MCprep before so thanks for sharing.

I see you are on windows using blender 2.77, curious - what version of windows are you on?

**Comment by ThePoptartCrpr** [comment] 2017-05-26 21:56
Can confirm that I'm still having the issue with 3.0.2.

![screenshot 207](https://cloud.githubusercontent.com/assets/25708063/26513957/7352db56-4223-11e7-9028-0077654137db.png)

**Comment by ThePoptartCrpr** [comment] 2017-05-26 21:56
Oh, and I'm on Windows 10.

**Comment by TheDuckCow** [comment] 2017-05-26 21:59
@ThePoptartCrpr could you try deleting the addon (press remove button), then close blender compeltely, re-open and try installing and enabling again to see if you get the same issue? That error could happen if you had the bad install version already.

**Comment by Axelen123** [comment] 2017-05-27 07:13
No Problem @TheDuckCow ! I am on Windows 10 The Creators Update (if that even matters lol)

**Comment by TheDuckCow** [comment] 2017-05-27 14:44
@Axelen123 okay perfect. Maybe there was one too many subfolders in the unzip or something, but glad to hear it's working. 

And again for @ThePoptartCrpr please try removing MCprep, closing blender, and re-opening and installing the addon through the interface. I definitely have confirmed installs on Windows 10 and v3.0.2 on blender 2.78 so I think that will solve your problem.

**Comment by ThePoptartCrpr** [comment] 2017-05-27 15:21
Oh, sure, I can try that.

**Comment by ThePoptartCrpr** [comment] 2017-06-01 17:54
I was able to install MCPrep 3.0.2 using that method.

Unfortunately, I've noticed something.

When I select everything and click "Prep Materials" and then "OK" from the Mineways menu (since I exported with Mineways) nothing happens. Nothing at all. No materials are prepped and nothing changes texture. And yes, I'm in Material mode. Everything's just black.

**Comment by TheDuckCow** [comment] 2017-06-02 13:44
Glad to hear it's working, closing the ticket for now.

**Comment by User1220-kk** [comment] 2021-10-04 10:14
My blender keeps on closing when i install this

**Comment by StandingPadAnimations** [comment] 2021-10-04 12:35
Wyat version of MCprep are you using and what version of Blender are you using?

**Comment by TheDuckCow** [comment] 2021-11-30 05:14
Closing this issue being a rather old thread, if there's still an issue of blender crashing (??!!) please let us know and open in a new issue, with more information like system, version of blender, version of MCprep etc.

**Closed by TheDuckCow** 2021-11-30 05:14 UTC
