### ISSUE TITLE
Mesh Swap not working in Blender 2.77

### ISSUE THREAD

**Issue by RarePika** [TheDuckCow/MCprep#6] opened 2016-06-13 01:53 UTC
In MCprep 2.1.3, meshswap was fixed in Blender 2.76. Now that Blender 2.77 is out, it needs fixing again. Please update soon! Thanks!

**Comment by TheDuckCow** [comment] 2016-06-16 14:28
On what way is it broken, what was working and then stopped? Screenshots can be useful too, thanks. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment] 2017-04-13 22:23
Closing due to staleness, my most recent tests indicate meshseapping currently works as intended.

**Closed by TheDuckCow** 2017-04-13 22:23 UTC
