### ISSUE TITLE
Mcprep not installing properly 

### ISSUE THREAD

**Issue by VortexAnimation** [TheDuckCow/MCprep#57] opened 2018-10-28 01:53 UTC
https://youtu.be/U8JlBj5-w28 for a video of my trying to install it anyone know if there is something im doing wrong or it just something to do with my blender files or something? At first i was having problems with it not show up on the side bar now when i install the addon the addon isn't even there for me to enable so i'm just going to use a older version for now also I've tried refreshing the addon page in user pref it doesnt show up still

**Comment by TheDuckCow** [comment] 2018-10-28 13:35
Thanks for putting that video together. Doing some testing myself, I think I know what the issue is now. 

When you download MCprep, **don't** unzip and rezip it, leave the download as-is. In my install video I only show that in case it unzipped for some people. 

*Let me know if that works!*

The issue that was occurring: By unzippping and rezipping, it actually renames the inner zipped folder from "MCprep_addon" to "MCprep v3.1.0 (2)" or similar, and this folder name with spaces and parentheses isn't allowed by Blender, so it just skips it. Personally I think that's sort of dumb, but not something I can control. 

Side note: you can always fully just manually install addons by just copying the unzipped (and properly named) folder into the your blender addons folder C:\\Users\<username\AppData\Roaming\blender....... and then you should see an addons folder. You'll probably also note you have duplicate, useless copies of the MCprpe folder with the bad names (e.g. MCprep v3.1.0 (2), etc), you can safely delete those.

Thankfully, this will hopefully be the very last time you ever have to do this. Once you get this one installed, it has a built-in updating now so it'll just install the update for you (whereas before it would only notify you that an update is out, and asks you to install it manually).

**Comment by TheDuckCow** [comment] 2018-10-28 13:53
Closing this issue as you mentioned this was resolved, thanks for working through this with me.

**Closed by TheDuckCow** 2018-10-28 13:53 UTC
