### ISSUE TITLE
exported .mtl files in obj export no longer contain references to texture images after MCprep

### ISSUE THREAD

**Issue by devmitch** [TheDuckCow/MCprep#252] opened 2021-11-09 10:09 UTC
I can import my .obj model (created with mineways) and export it again without changing anything, and the resultant .mtl file includes all the references to the textures (RBG, RGBA, Alpha). But if I import my model, prep materials with MCprep, and then export again, all the references are dropped. If I manually add them in using the old .mtl file, then the exported obj looks like it did before using MCprep (blurry, transparency not working correctly, etc). Any ideas?

.mtl file beforehand: https://pastebin.com/Bg6fXANB
.mtl file after blender export: https://pastebin.com/rxhzC0RU

**Comment by StandingPadAnimations** [comment] 2021-11-09 12:31
That's weird, MCprep shouldn't do that. I'll mark this as a bug for now

**Comment by StandingPadAnimations** [comment] 2021-11-09 18:52
I'll relabel this since it may be a Blender issue. As far as I can tell, you're trying to export a obj from Blender(which won't do much as the fixes MCprep does are Blender specific such as changing interpolation for image texture nodes from linear to closest and won't work elsewhere due to engine differences). If you want to use the obj elsewhere, I'd suggest changing the texture interpolation to closest outside of Blender

**Comment by StandingPadAnimations** [comment] 2021-11-09 18:55
To clarify, Mineways exports textures. The changes MCprep does involve nodes and not textures, which are specific to Blender. If you plan on using the obj in a different software, you have to do the changes in that software, not Blender.

**Comment by TheDuckCow** [comment] 2021-11-20 22:28
Thanks for commenting here StandingPadAnimations. 

To be clear, if you are trying to export something OUT of Blender in order to re-import into Minecraft, I'd say it's entirely expected to lose some information. MCprep's prep materials specifically sets up nodes and materials that *aren't* possible in the OBJ and MTL file format, and thus won't translate when being exported again. Things like custom falloffs, recolorization of nodes, animated texture support, etc.

Do ming sharing more about your use case? What are you trying to accomplish by exporting it from blender?

**Comment by TheDuckCow** [comment] 2021-11-30 05:09
Going to close this issue in the meantime as "intended behavior", given the limitations of the OBJ format and MCprep's intent of continuing to support more bespoke material shaders. But I'm still keen to hear more about your use case, if you have the time.

**Closed by TheDuckCow** 2021-11-30 05:09 UTC
Labels: user-troubleshoot
