### ISSUE TITLE
Warning when prepping materials on Dev version of Mcprep

### ISSUE THREAD

**Issue by Endertainer** [TheDuckCow/MCprep#212] opened 2021-06-06 22:41 UTC
So I tried the dev version of Mcprep for experiment. It works pretty well. Though, I kept getting this warning every time I prep material.
![blender_fyfZxJxXLU](https://user-images.githubusercontent.com/57242521/120942332-37fdc600-c763-11eb-89d3-aa6a0b57231b.png)
Here's what I got on the console.
[Mcprep_7-6-2021_Console_Copy.txt](https://github.com/TheDuckCow/MCprep/files/6605076/Mcprep_7-6-2021_Console_Copy.txt)

**Comment by TheDuckCow** [comment] 2021-06-08 03:55
Thanks for sharing that! And good to see some people are trying out the dev build, although it's not always in a stable state. 

My guess is that there are no rigs or any items or anything loading? This would be expected, since it's not a packaged release. If however rigs and such are showing up and you're getting errors, then it's something I need to look into. I'm hoping to release the update tomorrow (fingers crossed), so please let me know!

**Comment by TheDuckCow** [comment] 2021-06-11 18:24
Will close this in the meantime, as I'm fairly sure it's an issue with assets not being deployed with Dev (pretty much by design, since the assets are not checked into the repo itself which causes storage and history issues). Let me know if the released version is causing you issues however!

**Closed by TheDuckCow** 2021-06-11 18:24 UTC
Labels: user-troubleshoot
