### ISSUE TITLE
Imported model doesn't get renamed like in 2.7x

### ISSUE THREAD

**Issue by Endertainer** [TheDuckCow/MCprep#209] opened 2021-06-04 04:15 UTC
So when I first import a scanned Minecraft world in Blender 2.7x the blocks used to be named correctly. Like for example, a stone block is named stone in blender. But now in 2.8x to 2.9x, the blocks are named based on the obj file.
![blender_IIWJVPkICn](https://user-images.githubusercontent.com/57242521/120744708-909c4b80-c536-11eb-8e15-b9a24b32b1bc.png)
This is bad because it confuses me on which block is what. It also takes time to rename all of the blocks. 
I have an idea that whenever a model is imported by Mcprep, each block is named accordingly and stored in a collection. For example:

- Mineways world
  - Acacia Door
  - Glass
  - Stone
  - etc

I don't know if something like this can be implemented. But if it can, it would really help with file management since you know each block's name and it saves time renaming each block.

**Comment by StandingPadAnimations** [comment] 2021-06-04 17:32
I think it has to do with how MCprep imports objs but I'm not sure. My suggestion is to expand the window(the block names themselves are still there at the end of each name) and organize based of that

**Comment by TheDuckCow** [comment] 2021-06-05 15:54
Agreed it's not ideal. Part of the issue is the way blender imports objects in blender 2.8.

There may be some way for me to salvage this however. How do you feel about a solution where the collection is named after the world (e.g. "Mineways - {your-obj_name}"), and then the addon do best-effort renaming of the individual objects themselves? It may not be perfect, but can probably make it better.

**Comment by Endertainer** [comment] 2021-06-05 16:04
> Agreed it's not ideal. Part of the issue is the way blender imports objects in blender 2.8.
> 
> There may be some way for me to salvage this however. How do you feel about a solution where the collection is named after the world (e.g. "Mineways - {your-obj_name}"), and then the addon do best-effort renaming of the individual objects themselves? It may not be perfect, but can probably make it better.

Actually, that's what I have in mind. To have the the main collection named after the obj file. But yeah, that a great idea. It might not be perfect, but there's always a room for improvement. At least it would help save time.

**Comment by TheDuckCow** [comment] 2021-06-06 14:28
A status update I think you'll appreciate: https://github.com/TheDuckCow/MCprep/commit/a2389ae8932603951f05e6fbf4950c8e7c583770

The change is now submitted to the dev branch, and will be included in the next release (planned in the next several days).
![new world names](https://user-images.githubusercontent.com/2958461/120928212-b0a44a00-c6b1-11eb-80e4-ec77d883df4b.png)
 
This also has a really nice side effect of being able to import and manage multiple worlds without conflict. I'm going to close for now since it'll be coming out soon, thanks for the suggestion!

**Closed by TheDuckCow** 2021-06-06 14:28 UTC
Labels: enhancement
