### ISSUE TITLE
Error While Installing on Blender 2.93

### ISSUE THREAD

**Issue by DivyanshByte** [TheDuckCow/MCprep#208] opened 2021-06-03 03:50 UTC
I Tried reInstalling MCPrep on Latest Blender Version 2.93 because it was not working when I upgraded from 2.92.

But I am Keep Getting This Python Error:

![Error](https://user-images.githubusercontent.com/57246976/120583878-9fa6cf00-c44c-11eb-932d-1b629c9f5bf2.png)

I even Tried Reinstalling Blender But It Won't Work.

**Comment by MihinMUD** [comment] 2021-06-03 08:43
Same getting the same error
maybe needs an update for the addon to work with

**Comment by DivyanshByte** [comment] 2021-06-03 09:23
Yeah I think Its because Blender addons has been updated to Python 3.9.1 in Blender 2.93

**Comment by StandingPadAnimations** [comment] 2021-06-03 17:00
The 2.93 version of MCprep is coming out next week
![image](https://user-images.githubusercontent.com/75058058/120683437-3aaaa380-c463-11eb-923e-9c85796b0eb5.png)

**Comment by DivyanshByte** [comment] 2021-06-03 17:04
Ok

**Comment by Endertainer** [comment] 2021-06-04 01:59
I have this issue since I tried to use Blender 2.93 Alpha for experiments. Glad to see that there's a fix coming soon.

**Comment by JGBonkers** [comment] 2021-06-04 11:57
I keep having the same issue but on Blender 2.92 and 2.82, any ideas why?

**Comment by DivyanshByte** [comment] 2021-06-04 13:10
It Should Not Come for 2.92 as it was working best on Blender 2.92 for me

**Comment by TheDuckCow** [comment] 2021-06-04 14:41
Hi all, indeed the plan is to release the next update within 7 days (writing this so you can hold me accountable!)

However, @JGBonkers if you are having troubles with blender 2.92 or 2.82, it would hint at another problem. One general reference point: it's great to share screenshots, but my guess is the one above is the result of trying to re-tick the box after it failed to enable the first time. The "second" error popup is usually a consequence of the prior failure and not really helpful, I just know separately what the issue is for 2.93+. So for your 2.82/2.92 issue, could you see what the *first* popup message is, and post that into a new, separate issue thread? Thanks!

Thanks as always @StandingPadAnimations for being quicker than me in these replies!

**Comment by DivyanshByte** [comment] 2021-06-04 15:21
And @TheDuckCow However The Error Above Don't Came The First Time, It's The Error After Trying To Enable the addon Second or more time.

The First Error:
![The First Error](https://user-images.githubusercontent.com/57246976/120824924-839f4c80-c576-11eb-9e73-76360c8d09d5.png)

**Comment by StandingPadAnimations** [comment] 2021-06-04 17:31
That error means that Blender couldn't register the mcprep_mob_path property. Registering simply means Blender makes whatever is coded part of Blender. Since it couldn't register, some things in the MCprep UI will fail to work(and whatever that custom property's job was can't be done either). I assume it's the same for the other properties as well.

Basically, to put it, it's the registration issues that MCprep had to deal with in 2.93 since the Blender API was heavily changed(going from Python 3.7.7 to 3.9.1). While I have heard that MCprep worked in later versions of the 2.93 beta, it seems that was only temporary.

**Comment by DivyanshByte** [comment] 2021-06-05 02:35
So It Means It's An Error Of Blender API

**Comment by MayankYT1** [comment] 2021-06-05 15:10
So I have been having the same issue, so is it worth it to just download the version of blender which actually mcprep? if so, then which version of blender works with the latest version of mcprep? Or is it just better to wait for the bug to get fixed?

**Comment by DivyanshByte** [comment] 2021-06-05 15:43
@MayankYT1  It's Your Choice, If It is Important, Then You Should Use Blender 2.92 to work with latest version of MCprep. But If you can wait, Then Just Wait for MCprep to update for Blender 2.93 or latest version

**Comment by StandingPadAnimations** [comment] 2021-06-05 18:02
> So It Means It's An Error Of Blender API

No, it's not a Blender API bug, rather it was intended as they had to update it.

**Comment by DivyanshByte** [comment] 2021-06-07 03:35
I have a Question. Wether The 1.17 rigs, items, blocks will be added in MCprep 3.2.5 as It's Releasing Tomorrow 8th June

**Comment by StandingPadAnimations** [comment] 2021-06-07 16:54
Some might but not all since it's short notice

**Comment by StandingPadAnimations** [comment] 2021-06-07 18:18
That's beyond me

**Comment by TheDuckCow** [comment] 2021-06-08 03:56
I'm planning to release it tomorrow, not long after the official Minecraft 1.17 comes out (so I can also package the official texture updates too). Will close this thread once I have done so!

**Comment by MayankYT1** [comment] 2021-06-08 06:53
Perfect! Thanks a lot, I will be waiting for the release!

**Comment by DivyanshByte** [comment] 2021-06-08 08:27
> I'm planning to release it tomorrow, not long after the official Minecraft 1.17 comes out (so I can also package the official texture updates too). Will close this thread once I have done so!

But You can Also Get The New Textures from: [https://github.com/InventivetalentDev/minecraft-assets/](https://github.com/InventivetalentDev/minecraft-assets/). Just Change The Branch to The Version You Want. and download zip to get the textures.

**Comment by TheDuckCow** [comment] 2021-06-08 18:44
Yup, I actually already had them locally, I just wanted to be extra sure to use the latest release in case anything was changed last minute. In any event, the release is out now so I'm closing this issue. Thanks!

**Closed by TheDuckCow** 2021-06-08 18:44 UTC
Labels: bug

**Comment by DivyanshByte** [comment] 2021-06-09 03:26
Also I have an Question. How Do You get the Rigs As I cannot See download link for some rigs.

**Comment by TheDuckCow** [comment] 2021-06-10 01:06
All rigs that come with MCprep should be included in the original install. [See here](https://www.youtube.com/watch?v=xAtdxNiI0fA&list=PL8X_CzUEVBfaa9PD9lWm4HdQCxUhl62Zb&index=7) for more information, but if you are getting different behavior, please open a new issue so I can keep track!

**Comment by DivyanshByte** [comment] 2021-06-10 02:36
No My Question Was How do get the rigs? for some mobs.
