### ISSUE TITLE
Mob Spawning Random Objects

### ISSUE THREAD

**Issue by chaj87** [TheDuckCow/MCprep#2] opened 2016-03-24 20:07 UTC
When I spawn in any mob, the mob spawns in but with a lot of random squares, cubes, and and spheres.
![error snapshot](https://cloud.githubusercontent.com/assets/10554131/14029787/7bd7833e-f1da-11e5-8dbb-ab4e16f8ba51.PNG)

**Comment by TheDuckCow** [comment] 2016-03-25 12:23
Hey @chaj87, indeed this is a known new bug in 2.77, actually just due to how the new blender version appends groups. I am working on a fix but in the meantime, everything should stil work - you just (annoyingly) have to move these extra objects to another layer. For reference, they are what make up th bone shapes.

**Comment by chaj87** [comment] 2016-03-25 13:39
So i can just get an older version of Blender and it will work?

**Comment by TheDuckCow** [comment] 2016-03-25 14:07
That is correct - I can confirm that it works properly on both blender 2.76b and blender 2.75, and should work on any version down to blender 2.72.

**Comment by chaj87** [comment] 2016-03-25 14:13
Yep, I just tried 2.76a

**Comment by TheDuckCow** [comment] 2017-05-07 07:09
Adding this to milestone. While the initial issue was *reduced* by minimizing the size and placing bones into a better location, it's still not ideal. I will look into seeing what can be done about auto-removing the bone objects from the scene ("unlinking" from scene, but remaining in the file so they are still used as bone shapes) but I looked at it briefly before and is tricky due to again this change in how blender appends rigs and bone shapes now.

**Comment by TheDuckCow** [comment] 2019-05-26 16:10
Marking this as done from awhile ago, as this has been completed. Those bone rig objects no longer spawn in either 2.79 or 2.80.

**Closed by TheDuckCow** 2019-05-26 16:10 UTC
