### ISSUE TITLE
The JSON model does not contain any geometry elements, while trying to place lava using the Spawner.

### ISSUE THREAD

**Issue by haxor-dot** [TheDuckCow/MCprep#633] opened 2024-09-15 02:00 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I was trying to add **lava** to the scene using the addons **Block (model) Spawner**. Clicking the **Place:lava** button after selecting the **lava** model gives the error message in the status bar. I've tried adding the JSON manually, but it doesn't work.

![image](https://github.com/user-attachments/assets/ef64b81d-066b-4120-8c1c-9db9dcb15ccb)

### What steps are needed to produce the bug?

1. Create a new .blend file. 
2. Open the Sidebar pressing **N**
3. Go down to the **Spawner > Block (model) spawner**.
4. Scroll down or search for the **lava** model using the filtering options.
5. Selecting the lava, press **Place:lava**

### What version of MCprep are you using?

3.6.1.2

### What version of Blender are you using?

4.2.0

**Comment by StandingPadAnimations** [comment] 2024-09-15 02:20
As the error states, the JSON model for lava doesn't define geometry. Some models don't define geometry and instead depend on Minecraft's rendering code to have it hard-coded in the actual Minecraft source code. In those cases, we can't spawn the models because there's nothing in the JSON files telling us how to create the model. Since the error is working as intended, I'll close this report

**Closed as not planned by StandingPadAnimations** 2024-09-15 02:20 UTC
Labels: user-troubleshoot
