### ISSUE TITLE
1.17 Textures "unknown"

### ISSUE THREAD

**Issue by JonathanHutchins** [TheDuckCow/MCprep#241] opened 2021-09-08 17:36 UTC
Blocks such as Moss, Azalea, etc... from 1.17+ appear as an unknown material.
Light blocks not supported - again unknown material.
![image](https://user-images.githubusercontent.com/87151446/132557725-2f44f67d-013a-4e5c-ba36-f489a2f218d1.png)

**Comment by StandingPadAnimations** [comment] 2021-09-08 21:16
Try re-exporting the world. MCprep works with 1.17 blocks so it's mostly caused by the exporter having a hiccup. What exporter are you using?

**Comment by JonathanHutchins** [comment] 2021-09-08 21:22
> Try re-exporting the world. MCprep works with 1.17 blocks so it's mostly caused by the exporter having a hiccup. What exporter are you using?

I tried both mineways and jmc2obj, same result. Both are latest version. I could only remove the unknown materials by taking a new schematic save without 1.17 new blocks.

**Comment by StandingPadAnimations** [comment] 2021-09-08 21:28
Did you update mineways? Jmc doesnt support 1.17 as far as I know

**Comment by JonathanHutchins** [comment] 2021-09-09 06:46
> Did you update mineways? Jmc doesnt support 1.17 as far as I know

I can try and update it again, maybe I got a old version

**Comment by StandingPadAnimations** [comment] 2021-09-19 01:43
I'll go ahead and close this issue for now. Just comment again if there's still an issue

**Closed by StandingPadAnimations** 2021-09-19 01:43 UTC
Labels: user-troubleshoot
