### ISSUE TITLE
Villager's torso stops deforming after reopening blender

### ISSUE THREAD

**Issue by LarsK26001** [TheDuckCow/MCprep#307] opened 2022-06-26 07:26 UTC
When I add a villager to the scene, save blender, close, open and load the project again this happens:

<img width="960" alt="Villager isssue" src="https://user-images.githubusercontent.com/65247340/175803657-9360d141-cd65-40b6-9954-d42b58ee48a9.png">

The torso stops deforming with the rig.
I'm kind of a noob with blender but it looks like there's an issue with the lattice modifier missing it's object.

Before reopening:
<img width="181" alt="lattice" src="https://user-images.githubusercontent.com/65247340/175804045-e1bb024e-6e46-4773-8643-82cb4198391a.png">

After reopening:
<img width="186" alt="brokenlattice" src="https://user-images.githubusercontent.com/65247340/175804054-45322a0e-e799-4081-8889-2f7574807e3d.png">

**Comment by TheDuckCow** [comment] 2022-06-26 15:54
Thanks for posting - I was able to replicate in blender 3.0 as well. It looks like part of the issue is that for some reason, after saving and opening again, the object assigned to the Lattice modifier's object field gets cleared. It does _not_ happen in blender 2.93, so this makes me think something changed or broke with Blender 3.0+.

**The workaround**

You must assign the lattice as a fake user. I'll try to make MCprep automatically do this in a future release, but in the meantime, _right after spawning_, be sure to go into the outliner, change to orphan data, and under objects, find the lattice. Then click the shield icon to mark it as a "fake user" which will prevent blender from removing it (falsely thinking it is unused). Now you are save to save and close and reopen the file and things should be working fine.

<img width="441" alt="Screen Shot 2022-06-26 at 8 51 09 AM" src="https://user-images.githubusercontent.com/2958461/175822712-d2ba4af5-2c82-4029-a316-83fa2e4c98e5.png">

If you already spawned the character and the lattice already gone, there's not too much you can do, though you can attempt to respawn in a village and just copy over any animation data (probably easier than trying to remap the newly imported lattice to the original rig you had).

**Comment by TheDuckCow** [comment] 2022-07-01 04:12
Marking this as resolve as I have resolved the issue, and it will be fixed in the next release.

**Closed by TheDuckCow** 2022-07-01 04:12 UTC
Labels: bug, Known issue
