### ISSUE TITLE
The axe and sword and pretty much every other texture looks different and weird for items.

### ISSUE THREAD

**Issue by Whyyyy234** [TheDuckCow/MCprep#224] opened 2021-07-09 23:15 UTC
All the textures for the items look different and some parts of the pixels were either added or cut.

**Comment by TheDuckCow** [comment] 2021-07-10 14:50
Closing as a duplicate of https://github.com/TheDuckCow/MCprep/issues/213, the fix is being released in a near-term MCprep update, look forward to that! Thanks for reporting it though

**Closed by TheDuckCow** 2021-07-10 14:50 UTC
