### ISSUE TITLE
Effects folder directory preferences

### ISSUE THREAD

**Issue by zNightlord** [TheDuckCow/MCprep#338] opened 2022-08-25 09:24 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

MCPrep can't find the default directory the effects folder blend file, possibly due to using symlink.

<details> 
 <summary>
Blender Traceback
 </summary>
 
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\tracking.py", line 827, in wrapper
    res = function(self, context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 977, in execute
    update_effects_list(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 751, in update_effects_list
    load_geonode_effect_list(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 802, in load_geonode_effect_list
    with bpy.data.libraries.load(bfile) as (data_from, _):
OSError: load: C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\MCprep_resources\effects\geonodes\weather_effects_geo_by_the3pooka.blend failed to open blend file
```

</details> 

### What steps are needed to produce the bug?

Open Blender
Reload the effects `Reload assets`
Traceback prompt  show up.

### What version of MCprep are you using?

MCPrep 3.4.1

### What version of Blender are you using?

Blender 3.1

**Comment by TheDuckCow** [comment] 2022-08-25 14:07
Can you try restarting blender once more or reinstalling MCprep? This is very similar to an error caused by the auto updating code present in prior releases.On Aug 25, 2022 2:24 AM, Trung Phạm ***@***.***> wrote:
Did the issue happen after restarting Blender?
 Yes, the issue indeed continued after restarting Blender
Check known issues
 I have checked known issues, and my problem is different
What happened?
MCPrep can't find the default directory the effects folder blend file, possibly due to using symlink.
 
 
Blender Traceback
 
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\tracking.py", line 827, in wrapper
    res = function(self, context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 977, in execute
    update_effects_list(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 751, in update_effects_list
    load_geonode_effect_list(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\spawner\effects.py", line 802, in load_geonode_effect_list
    with bpy.data.libraries.load(bfile) as (data_from, _):
OSError: load: C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MCprep_addon\MCprep_resources\effects\geonodes\weather_effects_geo_by_the3pooka.blend failed to open blend file

 
What steps are needed to produce the bug?
Open Blender
Reload the effects Reload assets
Traceback prompt  show up.
What version of MCprep are you using?
MCPrep 3.4.1
What version of Blender are you using?
Blender 3.1

**Comment by zNightlord** [comment] 2022-08-25 15:14
> Can you try restarting blender once more or reinstalling MCprep? This is very similar to an error caused by the auto updating code present in prior releases

Normal reinstall through the zip file works normally, so the error in prior release is resolved. 

I think the cause of my issue is because of me using symbolic link to link MCPrep and run it in many version of Blender and the auto update don't like it, try to find the default directory to update and fail. 
I have to change out the effect directory for it to stop continue throw traceback.

**Comment by TheDuckCow** [comment] 2022-08-27 02:29
Let me know @zNightlord if symbolic links still pose an issue, as it should not be a problem (and if it is, it should be fixed in MCprep)

**Comment by TheDuckCow** [comment] 2022-09-15 21:17
Just replied to (and approved) your pull request, and linked it here.

**Closed** 2023-03-13 06:22 UTC
Labels: user-troubleshoot
