### ISSUE TITLE
How to remove fingers/mouth for non-player models

### ISSUE THREAD

**Issue by vvandert1** [TheDuckCow/MCprep#419] opened 2023-05-02 11:09 UTC
I would really like the basic minecraft models for blender, If there is a way please let me know. Otherwise, I will find one online if possible.

Hope image works :|
![image](https://user-images.githubusercontent.com/74796356/235650419-af65e0ec-bb05-464d-8d9a-47f42e11b15a.png)

**Comment by zNightlord** [comment] 2023-05-02 11:19
So you need a zombie that has no fingers?
The zombie would be just a steve humanoid model so you can find a human model rig and change the skin out for that.

**Comment by vvandert2alt** [comment] 2023-05-02 11:52
> So you need a zombie that has no fingers? The zombie would be just a steve humanoid model so you can find a human model rig and change the skin out for that.

Sry for different account, I'm not at my normal device
Thank you, I didn't think about that

**Comment by StandingPadAnimations** [comment] 2023-06-18 19:38
Assuming the issue is resolved, I'll close this now (you can still comment though if needed)

@vvandert1 @vvandert2alt, next time I would suggest asking on the MCprep Discord server as GitHub issues are reserved for bug reports (you can click the "Discord" button on the README or  click the link at the top of the bug report form)

**Closed by StandingPadAnimations** 2023-06-18 19:38 UTC
